/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jun 29 03:07:30 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008005
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_USB1_CTRL_H__
#define BCHP_USB1_CTRL_H__

/***************************************************************************
 *USB1_CTRL - USB Control Registers
 ***************************************************************************/
#define BCHP_USB1_CTRL_SETUP                     0x00480200 /* Setup Register */
#define BCHP_USB1_CTRL_PLL_CTL                   0x00480204 /* PLL Control Register */
#define BCHP_USB1_CTRL_FLADJ_VALUE               0x00480208 /* Frame Adjust Value */
#define BCHP_USB1_CTRL_EBRIDGE                   0x0048020c /* Control Register for EHCI Bridge */
#define BCHP_USB1_CTRL_OBRIDGE                   0x00480210 /* Control Register for OHCI Bridge */
#define BCHP_USB1_CTRL_MDIO                      0x00480214 /* MDIO Interface Programming Register */
#define BCHP_USB1_CTRL_MDIO2                     0x00480218 /* MDIO Interface Read Register */
#define BCHP_USB1_CTRL_TEST_PORT_CTL             0x0048021c /* Test Port Control Register */
#define BCHP_USB1_CTRL_USB_SIMCTL                0x00480220 /* Simulation Register */
#define BCHP_USB1_CTRL_USB_TESTCTL               0x00480224 /* Throutput Test Control */
#define BCHP_USB1_CTRL_USB_TESTMON               0x00480228 /* Throughput Test Monitor */
#define BCHP_USB1_CTRL_UTMI_CTL_1                0x0048022c /* UTMI Control Register */
#define BCHP_USB1_CTRL_UTMI_CTL_2                0x00480230 /* UTMI Control 2 Register */
#define BCHP_USB1_CTRL_USB_PM                    0x00480234 /* Power Management Register */
#define BCHP_USB1_CTRL_OHCI_ADDR_EXT             0x00480238 /* OHCI ADDRESS Extension */
#define BCHP_USB1_CTRL_SPARE1                    0x0048023c /* Spare1 Register for future use */
#define BCHP_USB1_CTRL_PLL_LDO_CTL               0x00480240 /* 28NM USBPHY LDO Control */
#define BCHP_USB1_CTRL_PLL_LDO_PLLBIAS           0x00480244 /* 28NM USBPHY PLLBIAS Control */
#define BCHP_USB1_CTRL_PLL_AFE_BG_CNTL           0x00480248 /* 28NM USBPHY AFE Bandgap Control */
#define BCHP_USB1_CTRL_PLL_NDIV_FRAC             0x0048024c /* PLL Feedback Divider Control Register */
#define BCHP_USB1_CTRL_SPARE2                    0x00480250 /* Spare2 Register for future use */
#define BCHP_USB1_CTRL_USB30_CTL1                0x00480260 /* USB30 CONTROL Register 1 */
#define BCHP_USB1_CTRL_USB30_CTL2                0x00480264 /* USB30 CONTROL Register 2 */
#define BCHP_USB1_CTRL_USB30_CTL3                0x00480268 /* USB30 CONTROL Register 3 */
#define BCHP_USB1_CTRL_USB30_CTL4                0x0048026c /* USB30 CONTROL Register 4 */

#endif /* #ifndef BCHP_USB1_CTRL_H__ */

/* End of File */
