/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jun 29 03:07:32 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008005
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_SHIMPHY_ADDR_CNTL_1_H__
#define BCHP_SHIMPHY_ADDR_CNTL_1_H__

/***************************************************************************
 *SHIMPHY_ADDR_CNTL_1 - DDR SHIMPHY   Control Registers 1
 ***************************************************************************/
#define BCHP_SHIMPHY_ADDR_CNTL_1_CONFIG          0x003c8000 /* SHIMPHY Config register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_SHIMPHY_REV_ID  0x003c8004 /* SHIMPHY Revision ID Register. */
#define BCHP_SHIMPHY_ADDR_CNTL_1_RESET           0x003c8008 /* DDR soft reset register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_DFI_CONTROL     0x003c8038 /* DFI Interface Control Register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_DFI_STATUS      0x003c803c /* DFI Interface Status Register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_PHY_LPM_STAT    0x003c8040 /* PHY Power Control Status Register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_IDLE_POWER_SAVING 0x003c8048 /* DDR PHY Idle power saving Control register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_PHY_STANDBY_EXIT 0x003c804c /* DDR PHY standby exit register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_ANALOG_BYPASS_CNTRL 0x003c806c /* Analog macro register bypass control */
#define BCHP_SHIMPHY_ADDR_CNTL_1_DDR_PLL_EXT_CLKSEL 0x003c8070 /* DDR PLL external clock select register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_TEST_MODE_CNTRL_REG 0x003c8074 /* SHIMPHY testport control register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_DISABLE_CHIP_BYPASS_PLL 0x003c807c /* DDR bypass pll mode disable register. */
#define BCHP_SHIMPHY_ADDR_CNTL_1_VECTOR_MODE_CLK_SEL 0x003c8088 /* DDR VECTOR PLL bypass mode clock select */
#define BCHP_SHIMPHY_ADDR_CNTL_1_DDR_PAD_CNTRL   0x003c808c /* DDR Pad control register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_CLK_GATE        0x003c8098 /* CLK_667_ENABLE Register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_SHIMPHY_STATUS  0x003c809c /* SHIMPHY Status Register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_CMD_DATA_FIFO   0x003c8028 /* Command and Data FIFO Status Register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_RD_DATAPATH     0x003c802c /* Read Datapath Status Register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_FLAG_BUS        0x003c8030 /* TP_OUT bus value Register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_MISC            0x003c8034 /* Miscellaneous Register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_SPARE0_RW       0x003c80a4 /* Spare register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_SPARE1_RW       0x003c80a8 /* Spare register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_SPARE0_RO       0x003c80ac /* Spare register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_SPARE1_RO       0x003c80b0 /* Spare register */
#define BCHP_SHIMPHY_ADDR_CNTL_1_DDR3_RESET_CNTRL 0x003c80b4 /* FORCE_DDR3_RESET Deassert  Register */

#endif /* #ifndef BCHP_SHIMPHY_ADDR_CNTL_1_H__ */

/* End of File */
