/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jun 29 03:07:33 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008005
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_DDR34_PHY_CONTROL_REGS_2_H__
#define BCHP_DDR34_PHY_CONTROL_REGS_2_H__

/***************************************************************************
 *DDR34_PHY_CONTROL_REGS_2 - DDR34 DDR34 physical interface control registers 2
 ***************************************************************************/
#define BCHP_DDR34_PHY_CONTROL_REGS_2_REVISION   0x003d6000 /* Address & Control revision register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PLL_STATUS 0x003d6004 /* PHY PLL status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PLL_CONFIG 0x003d6008 /* PHY PLL configuration register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PLL_CONTROL1 0x003d600c /* PHY PLL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PLL_CONTROL2 0x003d6010 /* PHY PLL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PLL_CONTROL3 0x003d6014 /* PHY PLL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PLL_DIVIDERS 0x003d6018 /* PHY PLL integer divider register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PLL_FRAC_DIVIDER 0x003d601c /* PHY PLL fractional divider register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PLL_SS_CONTROL 0x003d6020 /* PHY PLL spread spectrum control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PLL_SS_LIMIT 0x003d6024 /* PHY PLL spread spectrum limit register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_AUX_CONTROL 0x003d6028 /* Aux Control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_IDLE_PAD_CONTROL 0x003d602c /* Idle mode SSTL pad control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_DRIVE_PAD_CTL 0x003d6030 /* PVT Compensation control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_STATIC_PAD_CTL 0x003d6034 /* pad rx and tx characteristics control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_DRAM_CONFIG 0x003d6038 /* DRAM configuration register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_DRAM_TIMING1 0x003d603c /* DRAM timing register #1 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_DRAM_TIMING2 0x003d6040 /* DRAM timing register #2 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_DRAM_TIMING3 0x003d6044 /* DRAM timing register #3 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_DRAM_TIMING4 0x003d6048 /* DRAM timing register #4 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CALIBRATE 0x003d6060 /* PHY VDL calibration control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CALIB_STATUS1 0x003d6064 /* PHY VDL calibration status register #1 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CALIB_STATUS2 0x003d6068 /* PHY VDL calibration status register #2 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_MONITOR_CONTROL 0x003d606c /* PHY VDL delay monitoring control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_MONITOR_REF 0x003d6070 /* PHY VDL delay monitoring reference register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_MONITOR_STATUS 0x003d6074 /* PHY VDL delay monitoring status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_MONITOR_OVERRIDE 0x003d6078 /* PHY VDL delay monitoring override register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_MONITOR_OUT_CONTROL 0x003d607c /* PHY VDL delay monitoring output control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_MONITOR_OUT_STATUS 0x003d6080 /* PHY VDL delay monitoring output status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_MONITOR_OUT_STATUS_CLEAR 0x003d6084 /* PHY VDL delay monitoring output status clear register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD00 0x003d6090 /* DDR interface signal AD[00] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD01 0x003d6094 /* DDR interface signal AD[01] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD02 0x003d6098 /* DDR interface signal AD[02] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD03 0x003d609c /* DDR interface signal AD[03] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD04 0x003d60a0 /* DDR interface signal AD[04] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD05 0x003d60a4 /* DDR interface signal AD[05] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD06 0x003d60a8 /* DDR interface signal AD[06] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD07 0x003d60ac /* DDR interface signal AD[07] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD08 0x003d60b0 /* DDR interface signal AD[08] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD09 0x003d60b4 /* DDR interface signal AD[09] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD10 0x003d60b8 /* DDR interface signal AD[10] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD11 0x003d60bc /* DDR interface signal AD[11] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD12 0x003d60c0 /* DDR interface signal AD[12] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD13 0x003d60c4 /* DDR interface signal AD[13] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD14 0x003d60c8 /* DDR interface signal AD[14] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AD15 0x003d60cc /* DDR interface signal AD[15] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_BA0 0x003d60d0 /* DDR interface signal BA[0] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_BA1 0x003d60d4 /* DDR interface signal BA[1] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_BA2 0x003d60d8 /* DDR interface signal BA[2] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AUX0 0x003d60dc /* DDR interface signal AUX[0] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AUX1 0x003d60e0 /* DDR interface signal AUX[1] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_AUX2 0x003d60e4 /* DDR interface signal AUX[2] VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_CS0 0x003d60e8 /* DDR interface signal CS0 VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_CS1 0x003d60ec /* DDR interface signal CS1 VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_PAR 0x003d60f0 /* DDR interface signal PAR VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_RAS_N 0x003d60f4 /* DDR interface signal RAS_N VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_CAS_N 0x003d60f8 /* DDR interface signal CAS_N VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_CKE 0x003d60fc /* DDR interface signal CKE0 VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_RST_N 0x003d6100 /* DDR interface signal RST_N VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_ODT 0x003d6104 /* DDR interface signal ODT0 VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_WE_N 0x003d6108 /* DDR interface signal WE_N VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_DDR_CK_P 0x003d610c /* DDR interface signal DDR_CK-P VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CONTROL_DDR_CK_N 0x003d6110 /* DDR interface signal DDR_CK-N VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VDL_CLK_CONTROL 0x003d6114 /* DDR interface signal CLK VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_REFRESH    0x003d6130 /* Refresh engine controller */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_UPDATE_VDL 0x003d6134 /* Update VDL control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_UPDATE_VDL_SNOOP1 0x003d6138 /* Update VDL snoop control register #1 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_UPDATE_VDL_SNOOP2 0x003d613c /* Update VDL snoop control register #2 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_COMMAND_REG1 0x003d6140 /* DRAM Command Register #1 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_COMMAND_REG2 0x003d6144 /* DRAM Command Register #2 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_COMMAND_REG3 0x003d6148 /* DRAM Command Register #3 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_COMMAND_REG4 0x003d614c /* DRAM Command Register #4 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_COMMAND_REG_TIMER 0x003d6150 /* DRAM Command Timer Register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_MODE_REG0  0x003d6154 /* DDR3/DDR4/GDDR5M Mode Register 0 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_MODE_REG1  0x003d6158 /* DDR3/DDR4/GDDR5M Mode Register 1 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_MODE_REG2  0x003d615c /* DDR3/DDR4/GDDR5M Mode Register 2 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_MODE_REG3  0x003d6160 /* DDR3/DDR4/GDDR5M Mode Register 3 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_MODE_REG4  0x003d6164 /* DDR4/GDDR5M Mode Register 4 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_MODE_REG5  0x003d6168 /* DDR4/GDDR5M Mode Register 5 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_MODE_REG6  0x003d616c /* DDR4/GDDR5M Mode Register 6 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_MODE_REG7  0x003d6170 /* DDR4/GDDR5M Mode Register 7 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_MODE_REG15 0x003d6174 /* GDDR5M Mode Register 15 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_ALERT_CLEAR 0x003d6180 /* DDR4 Alert status clear register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_ALERT_STATUS 0x003d6184 /* DDR4 Alert status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_CA_PARITY  0x003d6188 /* DDR4 CA parity control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_CA_PLAYBACK_CONTROL 0x003d618c /* GDDR5M CA playback control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_CA_PLAYBACK_STATUS 0x003d6190 /* GDDR5M CA playback status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_WRITE_LEVELING_CONTROL 0x003d6194 /* Write leveling control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_WRITE_LEVELING_STATUS 0x003d6198 /* Write leveling status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_READ_ENABLE_CONTROL 0x003d619c /* Read enable test cycle control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_READ_ENABLE_STATUS 0x003d61a0 /* Read enable test cycle status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_TRAFFIC_GEN_LFSR_SEED 0x003d61b0 /* Traffic generator seed register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_TRAFFIC_GEN_ADDRESS1 0x003d61b4 /* Traffic generator address register #1 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_TRAFFIC_GEN_ADDRESS2 0x003d61b8 /* Traffic generator address register #2 */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_TRAFFIC_GEN_CONTROL 0x003d61bc /* Traffic generator control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_TRAFFIC_GEN_DATA_CONTROL 0x003d61c0 /* Traffic generator data control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_TRAFFIC_GEN_DQ_MASK 0x003d61c4 /* Traffic generator DQ mask register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_TRAFFIC_GEN_ECC_DQ_MASK 0x003d61c8 /* Traffic generator ECC DQ mask register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_TRAFFIC_GEN_STATUS 0x003d61cc /* Traffic generator status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_TRAFFIC_GEN_DQ_STATUS 0x003d61d0 /* Traffic generator DQ status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_TRAFFIC_GEN_ECC_STATUS 0x003d61d4 /* Traffic generator ECC DQ status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_TRAFFIC_GEN_ERR_CNT_CONTROL 0x003d61d8 /* Traffic generator error count control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_TRAFFIC_GEN_ERR_CNT_STATUS 0x003d61dc /* Traffic generator error count status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VIRTUAL_VTT_CONTROL 0x003d61f0 /* Virtual VTT Control and Status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VIRTUAL_VTT_STATUS 0x003d61f4 /* Virtual VTT Control and Status register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VIRTUAL_VTT_CONNECTIONS 0x003d61f8 /* Virtual VTT Connections register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VIRTUAL_VTT_OVERRIDE 0x003d61fc /* Virtual VTT Override register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_VREF_DAC_CONTROL 0x003d6200 /* VREF DAC Control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PHYBIST_CNTRL 0x003d6204 /* PhyBist Control Register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PHYBIST_SEED 0x003d6208 /* PhyBist Seed Register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PHYBIST_STATUS 0x003d620c /* PhyBist General Status Register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PHYBIST_CTL_STATUS 0x003d6210 /* PhyBist Per-Bit Control Pad Status Register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PHYBIST_DQ_STATUS 0x003d6214 /* PhyBist Per-Bit DQ Pad Status Register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_PHYBIST_MISC_STATUS 0x003d6218 /* PhyBist Per-Bit DM and CK Pad Status Register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_STANDBY_CONTROL 0x003d621c /* Standby Control register */
#define BCHP_DDR34_PHY_CONTROL_REGS_2_DEBUG_FREEZE_ENABLE 0x003d6220 /* Freeze-on-error enable register */

#endif /* #ifndef BCHP_DDR34_PHY_CONTROL_REGS_2_H__ */

/* End of File */
