/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jun 29 03:07:31 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008005
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_DDR34_PHY_BYTE_LANE_2_1_H__
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_H__

/***************************************************************************
 *DDR34_PHY_BYTE_LANE_2_1 - DDR34 DDR34 byte lane #2 control registers 1
 ***************************************************************************/
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_WR_DQS_P 0x003c6600 /* Byte Lane write DQS-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_WR_DQS_N 0x003c6604 /* Byte Lane write DQS-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_WR_DQ0 0x003c6608 /* Byte Lane write DQ0 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_WR_DQ1 0x003c660c /* Byte Lane write DQ1 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_WR_DQ2 0x003c6610 /* Byte Lane write DQ2 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_WR_DQ3 0x003c6614 /* Byte Lane write DQ3 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_WR_DQ4 0x003c6618 /* Byte Lane write DQ4 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_WR_DQ5 0x003c661c /* Byte Lane write DQ5 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_WR_DQ6 0x003c6620 /* Byte Lane write DQ6 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_WR_DQ7 0x003c6624 /* Byte Lane write DQ7 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_WR_DM 0x003c6628 /* Byte Lane write DM VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_WR_EDC 0x003c662c /* Byte Lane write EDC VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQSP 0x003c6630 /* Byte Lane read DQSP VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQSN 0x003c6634 /* Byte Lane read DQSP VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ0P 0x003c6638 /* Byte Lane read DQ0-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ0N 0x003c663c /* Byte Lane read DQ0-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ1P 0x003c6640 /* Byte Lane read DQ1-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ1N 0x003c6644 /* Byte Lane read DQ1-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ2P 0x003c6648 /* Byte Lane read DQ2-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ2N 0x003c664c /* Byte Lane read DQ2-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ3P 0x003c6650 /* Byte Lane read DQ3-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ3N 0x003c6654 /* Byte Lane read DQ3-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ4P 0x003c6658 /* Byte Lane read DQ4-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ4N 0x003c665c /* Byte Lane read DQ4-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ5P 0x003c6660 /* Byte Lane read DQ5-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ5N 0x003c6664 /* Byte Lane read DQ5-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ6P 0x003c6668 /* Byte Lane read DQ6-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ6N 0x003c666c /* Byte Lane read DQ6-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ7P 0x003c6670 /* Byte Lane read DQ7-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DQ7N 0x003c6674 /* Byte Lane read DQ7-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DMP 0x003c6678 /* Byte Lane read DM-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_DMN 0x003c667c /* Byte Lane read DM-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_EDCP 0x003c6680 /* Byte Lane read EDC-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_EDCN 0x003c6684 /* Byte Lane read EDC-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CONTROL_BL_RD_EN 0x003c6688 /* Byte Lane read enable VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_VDL_CLK_CONTROL_BL 0x003c6690 /* Byte Lane write leveling VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_RD_EN_DLY_CYC_BL 0x003c66a0 /* Byte Lane read enable bit-clock cycle delay control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_WL_DLY_CYC_BL 0x003c66b0 /* Byte Lane write leveling bit-clock cycle delay control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_READ_CONTROL 0x003c66b4 /* Word Lane read channel control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_READ_WATCHDOG_CONTROL 0x003c66b8 /* Word Lane read channel watchdog timer control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_READ_FIFO_ADDR 0x003c66c0 /* Word Lane read channel watchdog timer control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_READ_FIFO_DATA 0x003c66c4 /* Read fifo data register, first data */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_READ_FIFO_STATUS 0x003c66d0 /* Read fifo status register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_READ_FIFO_CLEAR 0x003c66d4 /* Read fifo status clear register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_DM_EDC_CONTROL 0x003c66d8 /* Word Lane DM & EDC signal control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_IDLE_PAD_CONTROL 0x003c66dc /* Idle mode SSTL pad control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_DRIVE_PAD_CTL 0x003c66e0 /* SSTL pad drive characteristics control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_STATIC_PAD_CTL 0x003c66e4 /* pad rx and tx characteristics control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_WR_PREAMBLE_MODE 0x003c66e8 /* Write cycle preamble control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_EDC_DPD_CONTROL_BL 0x003c66ec /* Byte Lane GDDR5M EDC digital phase detector control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_EDC_DPD_STATUS_BL 0x003c66f0 /* Byte Lane GDDR5M EDC digital phase detector status register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_EDC_DPD_OUT_CONTROL_BL 0x003c66f4 /* Byte Lane GDDR5M EDC digital phase detector output signal control register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_EDC_DPD_OUT_STATUS_BL 0x003c66f8 /* Byte Lane GDDR5M EDC digital phase detector output signal status register */
#define BCHP_DDR34_PHY_BYTE_LANE_2_1_EDC_DPD_OUT_STATUS_CLEAR_BL 0x003c66fc /* Byte Lane GDDR5M EDC digital phase detector output signal status clear register */

#endif /* #ifndef BCHP_DDR34_PHY_BYTE_LANE_2_1_H__ */

/* End of File */
