/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jun 29 03:07:31 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008005
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_MEMC_ARB_1_H__
#define BCHP_MEMC_ARB_1_H__

/***************************************************************************
 *MEMC_ARB_1 - Arbitration & Client Info Registers 1
 ***************************************************************************/
#define BCHP_MEMC_ARB_1_PHY_DEBUG_REGISTER       0x003c1000 /* MEMC CORE and IOBUF Interface Debug Register */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_0            0x003c1004 /* Client Programming register for client 0. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_1            0x003c1008 /* Client Programming register for client 1. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_2            0x003c100c /* Client Programming register for client 2. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_3            0x003c1010 /* Client Programming register for client 3. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_4            0x003c1014 /* Client Programming register for client 4. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_5            0x003c1018 /* Client Programming register for client 5. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_6            0x003c101c /* Client Programming register for client 6. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_7            0x003c1020 /* Client Programming register for client 7. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_8            0x003c1024 /* Client Programming register for client 8. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_9            0x003c1028 /* Client Programming register for client 9. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_10           0x003c102c /* Client Programming register for client 10. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_11           0x003c1030 /* Client Programming register for client 11. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_12           0x003c1034 /* Client Programming register for client 12. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_13           0x003c1038 /* Client Programming register for client 13. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_14           0x003c103c /* Client Programming register for client 14. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_15           0x003c1040 /* Client Programming register for client 15. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_16           0x003c1044 /* Client Programming register for client 16. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_17           0x003c1048 /* Client Programming register for client 17. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_18           0x003c104c /* Client Programming register for client 18. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_19           0x003c1050 /* Client Programming register for client 19. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_20           0x003c1054 /* Client Programming register for client 20. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_21           0x003c1058 /* Client Programming register for client 21. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_22           0x003c105c /* Client Programming register for client 22. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_23           0x003c1060 /* Client Programming register for client 23. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_24           0x003c1064 /* Client Programming register for client 24. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_25           0x003c1068 /* Client Programming register for client 25. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_26           0x003c106c /* Client Programming register for client 26. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_27           0x003c1070 /* Client Programming register for client 27. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_28           0x003c1074 /* Client Programming register for client 28. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_29           0x003c1078 /* Client Programming register for client 29. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_30           0x003c107c /* Client Programming register for client 30. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_31           0x003c1080 /* Client Programming register for client 31. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_32           0x003c1084 /* Client Programming register for client 32. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_33           0x003c1088 /* Client Programming register for client 33. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_34           0x003c108c /* Client Programming register for client 34. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_35           0x003c1090 /* Client Programming register for client 35. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_36           0x003c1094 /* Client Programming register for client 36. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_37           0x003c1098 /* Client Programming register for client 37. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_38           0x003c109c /* Client Programming register for client 38. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_39           0x003c10a0 /* Client Programming register for client 39. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_40           0x003c10a4 /* Client Programming register for client 40. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_41           0x003c10a8 /* Client Programming register for client 41. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_42           0x003c10ac /* Client Programming register for client 42. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_43           0x003c10b0 /* Client Programming register for client 43. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_44           0x003c10b4 /* Client Programming register for client 44. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_45           0x003c10b8 /* Client Programming register for client 45. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_46           0x003c10bc /* Client Programming register for client 46. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_47           0x003c10c0 /* Client Programming register for client 47. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_48           0x003c10c4 /* Client Programming register for client 48. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_49           0x003c10c8 /* Client Programming register for client 49. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_50           0x003c10cc /* Client Programming register for client 50. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_51           0x003c10d0 /* Client Programming register for client 51. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_52           0x003c10d4 /* Client Programming register for client 52. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_53           0x003c10d8 /* Client Programming register for client 53. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_54           0x003c10dc /* Client Programming register for client 54. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_55           0x003c10e0 /* Client Programming register for client 55. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_56           0x003c10e4 /* Client Programming register for client 56. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_57           0x003c10e8 /* Client Programming register for client 57. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_58           0x003c10ec /* Client Programming register for client 58. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_59           0x003c10f0 /* Client Programming register for client 59. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_60           0x003c10f4 /* Client Programming register for client 60. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_61           0x003c10f8 /* Client Programming register for client 61. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_62           0x003c10fc /* Client Programming register for client 62. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_63           0x003c1100 /* Client Programming register for client 63. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_64           0x003c1104 /* Client Programming register for client 64. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_65           0x003c1108 /* Client Programming register for client 65. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_66           0x003c110c /* Client Programming register for client 66. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_67           0x003c1110 /* Client Programming register for client 67. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_68           0x003c1114 /* Client Programming register for client 68. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_69           0x003c1118 /* Client Programming register for client 69. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_70           0x003c111c /* Client Programming register for client 70. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_71           0x003c1120 /* Client Programming register for client 71. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_72           0x003c1124 /* Client Programming register for client 72. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_73           0x003c1128 /* Client Programming register for client 73. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_74           0x003c112c /* Client Programming register for client 74. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_75           0x003c1130 /* Client Programming register for client 75. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_76           0x003c1134 /* Client Programming register for client 76. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_77           0x003c1138 /* Client Programming register for client 77. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_78           0x003c113c /* Client Programming register for client 78. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_79           0x003c1140 /* Client Programming register for client 79. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_80           0x003c1144 /* Client Programming register for client 80. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_81           0x003c1148 /* Client Programming register for client 81. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_82           0x003c114c /* Client Programming register for client 82. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_83           0x003c1150 /* Client Programming register for client 83. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_84           0x003c1154 /* Client Programming register for client 84. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_85           0x003c1158 /* Client Programming register for client 85. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_86           0x003c115c /* Client Programming register for client 86. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_87           0x003c1160 /* Client Programming register for client 87. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_88           0x003c1164 /* Client Programming register for client 88. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_89           0x003c1168 /* Client Programming register for client 89. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_90           0x003c116c /* Client Programming register for client 90. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_91           0x003c1170 /* Client Programming register for client 91. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_92           0x003c1174 /* Client Programming register for client 92. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_93           0x003c1178 /* Client Programming register for client 93. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_94           0x003c117c /* Client Programming register for client 94. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_95           0x003c1180 /* Client Programming register for client 95. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_96           0x003c1184 /* Client Programming register for client 96. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_97           0x003c1188 /* Client Programming register for client 97. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_98           0x003c118c /* Client Programming register for client 98. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_99           0x003c1190 /* Client Programming register for client 99. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_100          0x003c1194 /* Client Programming register for client 100. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_101          0x003c1198 /* Client Programming register for client 101. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_102          0x003c119c /* Client Programming register for client 102. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_103          0x003c11a0 /* Client Programming register for client 103. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_104          0x003c11a4 /* Client Programming register for client 104. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_105          0x003c11a8 /* Client Programming register for client 105. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_106          0x003c11ac /* Client Programming register for client 106. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_107          0x003c11b0 /* Client Programming register for client 107. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_108          0x003c11b4 /* Client Programming register for client 108. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_109          0x003c11b8 /* Client Programming register for client 109. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_110          0x003c11bc /* Client Programming register for client 110. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_111          0x003c11c0 /* Client Programming register for client 111. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_112          0x003c11c4 /* Client Programming register for client 112. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_113          0x003c11c8 /* Client Programming register for client 113. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_114          0x003c11cc /* Client Programming register for client 114. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_115          0x003c11d0 /* Client Programming register for client 115. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_116          0x003c11d4 /* Client Programming register for client 116. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_117          0x003c11d8 /* Client Programming register for client 117. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_118          0x003c11dc /* Client Programming register for client 118. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_119          0x003c11e0 /* Client Programming register for client 119. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_120          0x003c11e4 /* Client Programming register for client 120. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_121          0x003c11e8 /* Client Programming register for client 121. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_122          0x003c11ec /* Client Programming register for client 122. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_123          0x003c11f0 /* Client Programming register for client 123. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_124          0x003c11f4 /* Client Programming register for client 124. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_125          0x003c11f8 /* Client Programming register for client 125. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_126          0x003c11fc /* Client Programming register for client 126. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_127          0x003c1200 /* Client Programming register for client 127 */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_128          0x003c1204 /* Client Programming register for client 128. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_129          0x003c1208 /* Client Programming register for client 129. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_130          0x003c120c /* Client Programming register for client 130. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_131          0x003c1210 /* Client Programming register for client 131. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_132          0x003c1214 /* Client Programming register for client 132. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_133          0x003c1218 /* Client Programming register for client 133. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_134          0x003c121c /* Client Programming register for client 134. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_135          0x003c1220 /* Client Programming register for client 135. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_136          0x003c1224 /* Client Programming register for client 136. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_137          0x003c1228 /* Client Programming register for client 137. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_138          0x003c122c /* Client Programming register for client 138. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_139          0x003c1230 /* Client Programming register for client 139. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_140          0x003c1234 /* Client Programming register for client 140. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_141          0x003c1238 /* Client Programming register for client 141. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_142          0x003c123c /* Client Programming register for client 142. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_143          0x003c1240 /* Client Programming register for client 143. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_144          0x003c1244 /* Client Programming register for client 144. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_145          0x003c1248 /* Client Programming register for client 145. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_146          0x003c124c /* Client Programming register for client 146. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_147          0x003c1250 /* Client Programming register for client 147. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_148          0x003c1254 /* Client Programming register for client 148. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_149          0x003c1258 /* Client Programming register for client 149. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_150          0x003c125c /* Client Programming register for client 150. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_151          0x003c1260 /* Client Programming register for client 151. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_152          0x003c1264 /* Client Programming register for client 152. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_153          0x003c1268 /* Client Programming register for client 153. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_154          0x003c126c /* Client Programming register for client 154. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_155          0x003c1270 /* Client Programming register for client 155. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_156          0x003c1274 /* Client Programming register for client 156. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_157          0x003c1278 /* Client Programming register for client 157. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_158          0x003c127c /* Client Programming register for client 158. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_159          0x003c1280 /* Client Programming register for client 159. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_160          0x003c1284 /* Client Programming register for client 160. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_161          0x003c1288 /* Client Programming register for client 161. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_162          0x003c128c /* Client Programming register for client 162. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_163          0x003c1290 /* Client Programming register for client 163. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_164          0x003c1294 /* Client Programming register for client 164. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_165          0x003c1298 /* Client Programming register for client 165. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_166          0x003c129c /* Client Programming register for client 166. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_167          0x003c12a0 /* Client Programming register for client 167. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_168          0x003c12a4 /* Client Programming register for client 168. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_169          0x003c12a8 /* Client Programming register for client 169. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_170          0x003c12ac /* Client Programming register for client 170. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_171          0x003c12b0 /* Client Programming register for client 171. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_172          0x003c12b4 /* Client Programming register for client 172. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_173          0x003c12b8 /* Client Programming register for client 173. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_174          0x003c12bc /* Client Programming register for client 174. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_175          0x003c12c0 /* Client Programming register for client 175. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_176          0x003c12c4 /* Client Programming register for client 176. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_177          0x003c12c8 /* Client Programming register for client 177. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_178          0x003c12cc /* Client Programming register for client 178. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_179          0x003c12d0 /* Client Programming register for client 179. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_180          0x003c12d4 /* Client Programming register for client 180. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_181          0x003c12d8 /* Client Programming register for client 181. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_182          0x003c12dc /* Client Programming register for client 182. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_183          0x003c12e0 /* Client Programming register for client 183. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_184          0x003c12e4 /* Client Programming register for client 184. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_185          0x003c12e8 /* Client Programming register for client 185. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_186          0x003c12ec /* Client Programming register for client 186. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_187          0x003c12f0 /* Client Programming register for client 187. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_188          0x003c12f4 /* Client Programming register for client 188. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_189          0x003c12f8 /* Client Programming register for client 189. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_190          0x003c12fc /* Client Programming register for client 190. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_191          0x003c1300 /* Client Programming register for client 191. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_192          0x003c1304 /* Client Programming register for client 192. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_193          0x003c1308 /* Client Programming register for client 193. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_194          0x003c130c /* Client Programming register for client 194. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_195          0x003c1310 /* Client Programming register for client 195. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_196          0x003c1314 /* Client Programming register for client 196. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_197          0x003c1318 /* Client Programming register for client 197. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_198          0x003c131c /* Client Programming register for client 198. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_199          0x003c1320 /* Client Programming register for client 199. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_200          0x003c1324 /* Client Programming register for client 200. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_201          0x003c1328 /* Client Programming register for client 201. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_202          0x003c132c /* Client Programming register for client 202. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_203          0x003c1330 /* Client Programming register for client 203. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_204          0x003c1334 /* Client Programming register for client 204. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_205          0x003c1338 /* Client Programming register for client 205. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_206          0x003c133c /* Client Programming register for client 206. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_207          0x003c1340 /* Client Programming register for client 207. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_208          0x003c1344 /* Client Programming register for client 208. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_209          0x003c1348 /* Client Programming register for client 209. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_210          0x003c134c /* Client Programming register for client 210. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_211          0x003c1350 /* Client Programming register for client 211. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_212          0x003c1354 /* Client Programming register for client 212. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_213          0x003c1358 /* Client Programming register for client 213. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_214          0x003c135c /* Client Programming register for client 214. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_215          0x003c1360 /* Client Programming register for client 215. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_216          0x003c1364 /* Client Programming register for client 216. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_217          0x003c1368 /* Client Programming register for client 217. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_218          0x003c136c /* Client Programming register for client 218. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_219          0x003c1370 /* Client Programming register for client 219. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_220          0x003c1374 /* Client Programming register for client 220. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_221          0x003c1378 /* Client Programming register for client 221. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_222          0x003c137c /* Client Programming register for client 222. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_223          0x003c1380 /* Client Programming register for client 223. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_224          0x003c1384 /* Client Programming register for client 224. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_225          0x003c1388 /* Client Programming register for client 225. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_226          0x003c138c /* Client Programming register for client 226. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_227          0x003c1390 /* Client Programming register for client 227. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_228          0x003c1394 /* Client Programming register for client 228. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_229          0x003c1398 /* Client Programming register for client 229. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_230          0x003c139c /* Client Programming register for client 230. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_231          0x003c13a0 /* Client Programming register for client 231. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_232          0x003c13a4 /* Client Programming register for client 232. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_233          0x003c13a8 /* Client Programming register for client 233. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_234          0x003c13ac /* Client Programming register for client 234. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_235          0x003c13b0 /* Client Programming register for client 235. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_236          0x003c13b4 /* Client Programming register for client 236. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_237          0x003c13b8 /* Client Programming register for client 237. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_238          0x003c13bc /* Client Programming register for client 238. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_239          0x003c13c0 /* Client Programming register for client 239. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_240          0x003c13c4 /* Client Programming register for client 240. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_241          0x003c13c8 /* Client Programming register for client 241. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_242          0x003c13cc /* Client Programming register for client 242. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_243          0x003c13d0 /* Client Programming register for client 243. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_244          0x003c13d4 /* Client Programming register for client 244. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_245          0x003c13d8 /* Client Programming register for client 245. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_246          0x003c13dc /* Client Programming register for client 246. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_247          0x003c13e0 /* Client Programming register for client 247. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_248          0x003c13e4 /* Client Programming register for client 248. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_249          0x003c13e8 /* Client Programming register for client 249. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_250          0x003c13ec /* Client Programming register for client 250. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_251          0x003c13f0 /* Client Programming register for client 251. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_252          0x003c13f4 /* Client Programming register for client 252. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_253          0x003c13f8 /* Client Programming register for client 253. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_254          0x003c13fc /* Client Programming register for client 254. */
#define BCHP_MEMC_ARB_1_CLIENT_INFO_255          0x003c1400 /* Client Programming register for client 255 */
#define BCHP_MEMC_ARB_1_REQ_MASK_0               0x003c1404 /* Request Mask register for Clients 0 to 31 */
#define BCHP_MEMC_ARB_1_REQ_MASK_1               0x003c1408 /* Request Mask register for Clients 32 to 63 */
#define BCHP_MEMC_ARB_1_REQ_MASK_2               0x003c140c /* Request Mask register for Clients 64 to 95 */
#define BCHP_MEMC_ARB_1_REQ_MASK_3               0x003c1410 /* Request Mask register for Clients 96 to 127 */
#define BCHP_MEMC_ARB_1_REQ_MASK_4               0x003c1414 /* Request Mask register for Clients 128 to 159 */
#define BCHP_MEMC_ARB_1_REQ_MASK_5               0x003c1418 /* Request Mask register for Clients 160 to 191 */
#define BCHP_MEMC_ARB_1_REQ_MASK_6               0x003c141c /* Request Mask register for Clients 192 to 223 */
#define BCHP_MEMC_ARB_1_REQ_MASK_7               0x003c1420 /* Request Mask register for Clients 224 to 255 */
#define BCHP_MEMC_ARB_1_ARB_WINNER               0x003c1424 /* SCB-Arbitration Winner. */
#define BCHP_MEMC_ARB_1_RTS_ERR_0                0x003c1428 /* RTS Deadline miss register for Clients 0 to 31 */
#define BCHP_MEMC_ARB_1_RTS_ERR_1                0x003c142c /* RTS Deadline miss register for Clients 32 to 63 */
#define BCHP_MEMC_ARB_1_RTS_ERR_2                0x003c1430 /* RTS Deadline miss register for Clients 64 to 95 */
#define BCHP_MEMC_ARB_1_RTS_ERR_3                0x003c1434 /* RTS Deadline miss register for Clients 96 to 127 */
#define BCHP_MEMC_ARB_1_RTS_ERR_4                0x003c1438 /* RTS Deadline miss register for Clients 128 to 159 */
#define BCHP_MEMC_ARB_1_RTS_ERR_5                0x003c143c /* RTS Deadline miss register for Clients 160 to 191 */
#define BCHP_MEMC_ARB_1_RTS_ERR_6                0x003c1440 /* RTS Deadline miss register for Clients 192 to 223 */
#define BCHP_MEMC_ARB_1_RTS_ERR_7                0x003c1444 /* RTS Deadline miss register for Clients 224 to 255 */
#define BCHP_MEMC_ARB_1_FULLNESS_THRESHOLD       0x003c1448 /* Arbiter fullness threshold register */
#define BCHP_MEMC_ARB_1_FULLNESS_UPDATE_HOLDOFF  0x003c144c /* SCB and MCP Write Fullness Update Holdoff register */
#define BCHP_MEMC_ARB_1_MINIMUM_COMMAND_SIZE     0x003c1450 /* Minimum command size register */
#define BCHP_MEMC_ARB_1_MINIMUM_COMMAND_SIZE2    0x003c1454 /* Minimum command size register for UBUS */
#define BCHP_MEMC_ARB_1_RTS_ERR_INFO_WRITE_CLEAR 0x003c1458 /* MEMC RTS_ERR_INFO write clear register */
#define BCHP_MEMC_ARB_1_SCB_ARBITER_DEBUG_REGISTER 0x003c145c /* MEMC SCB Interface and Arbiter State Machine and FIFO Debug Register */
#define BCHP_MEMC_ARB_1_SPARE_1                  0x003c1460 /* Spare Register 1 . */
#define BCHP_MEMC_ARB_1_SPARE_2                  0x003c1464 /* Spare Register 2 . */
#define BCHP_MEMC_ARB_1_SPARE_RO_1               0x003c1468 /* Read only Spare Register 1 . */
#define BCHP_MEMC_ARB_1_SPARE_RO_2               0x003c146c /* Read only Spare Register 2 . */
#define BCHP_MEMC_ARB_1_CLIENT_INIT_ENABLE       0x003c1470 /* "Enable for client init block." */
#define BCHP_MEMC_ARB_1_CLIENT_INIT_COUNTER_THRESH 0x003c1474 /* "Client init block counter threshold value" */
#define BCHP_MEMC_ARB_1_CLIENT_INIT_ERROR_INTERRUPT 0x003c1478 /* "Client init error interrupt" */
#define BCHP_MEMC_ARB_1_CLIENT_INIT_ERROR_WRITE_CLEAR 0x003c147c /* "Client init error write clear" */
#define BCHP_MEMC_ARB_1_CLIENT_INIT_ERROR_INFO   0x003c1480 /* "Client init error violation info" */
#define BCHP_MEMC_ARB_1_CLIENT_INIT_SW_INIT      0x003c1484 /* "Client init software init" */
#define BCHP_MEMC_ARB_1_CLIENT_INIT_STATUS       0x003c1488 /* "Client init status and debug register" */

#endif /* #ifndef BCHP_MEMC_ARB_1_H__ */

/* End of File */
