/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jun 29 03:07:32 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008005
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_DDR34_PHY_BYTE_LANE_0_1_H__
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_H__

/***************************************************************************
 *DDR34_PHY_BYTE_LANE_0_1 - DDR34 DDR34 byte lane #0 control registers 1
 ***************************************************************************/
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_WR_DQS_P 0x003c6400 /* Byte Lane write DQS-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_WR_DQS_N 0x003c6404 /* Byte Lane write DQS-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_WR_DQ0 0x003c6408 /* Byte Lane write DQ0 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_WR_DQ1 0x003c640c /* Byte Lane write DQ1 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_WR_DQ2 0x003c6410 /* Byte Lane write DQ2 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_WR_DQ3 0x003c6414 /* Byte Lane write DQ3 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_WR_DQ4 0x003c6418 /* Byte Lane write DQ4 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_WR_DQ5 0x003c641c /* Byte Lane write DQ5 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_WR_DQ6 0x003c6420 /* Byte Lane write DQ6 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_WR_DQ7 0x003c6424 /* Byte Lane write DQ7 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_WR_DM 0x003c6428 /* Byte Lane write DM VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_WR_EDC 0x003c642c /* Byte Lane write EDC VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQSP 0x003c6430 /* Byte Lane read DQSP VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQSN 0x003c6434 /* Byte Lane read DQSP VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ0P 0x003c6438 /* Byte Lane read DQ0-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ0N 0x003c643c /* Byte Lane read DQ0-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ1P 0x003c6440 /* Byte Lane read DQ1-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ1N 0x003c6444 /* Byte Lane read DQ1-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ2P 0x003c6448 /* Byte Lane read DQ2-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ2N 0x003c644c /* Byte Lane read DQ2-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ3P 0x003c6450 /* Byte Lane read DQ3-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ3N 0x003c6454 /* Byte Lane read DQ3-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ4P 0x003c6458 /* Byte Lane read DQ4-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ4N 0x003c645c /* Byte Lane read DQ4-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ5P 0x003c6460 /* Byte Lane read DQ5-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ5N 0x003c6464 /* Byte Lane read DQ5-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ6P 0x003c6468 /* Byte Lane read DQ6-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ6N 0x003c646c /* Byte Lane read DQ6-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ7P 0x003c6470 /* Byte Lane read DQ7-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DQ7N 0x003c6474 /* Byte Lane read DQ7-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DMP 0x003c6478 /* Byte Lane read DM-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_DMN 0x003c647c /* Byte Lane read DM-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_EDCP 0x003c6480 /* Byte Lane read EDC-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_EDCN 0x003c6484 /* Byte Lane read EDC-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CONTROL_BL_RD_EN 0x003c6488 /* Byte Lane read enable VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_VDL_CLK_CONTROL_BL 0x003c6490 /* Byte Lane write leveling VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_RD_EN_DLY_CYC_BL 0x003c64a0 /* Byte Lane read enable bit-clock cycle delay control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_WL_DLY_CYC_BL 0x003c64b0 /* Byte Lane write leveling bit-clock cycle delay control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_READ_CONTROL 0x003c64b4 /* Word Lane read channel control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_READ_WATCHDOG_CONTROL 0x003c64b8 /* Word Lane read channel watchdog timer control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_READ_FIFO_ADDR 0x003c64c0 /* Word Lane read channel watchdog timer control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_READ_FIFO_DATA 0x003c64c4 /* Read fifo data register, first data */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_READ_FIFO_STATUS 0x003c64d0 /* Read fifo status register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_READ_FIFO_CLEAR 0x003c64d4 /* Read fifo status clear register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_DM_EDC_CONTROL 0x003c64d8 /* Word Lane DM & EDC signal control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_IDLE_PAD_CONTROL 0x003c64dc /* Idle mode SSTL pad control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_DRIVE_PAD_CTL 0x003c64e0 /* SSTL pad drive characteristics control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_STATIC_PAD_CTL 0x003c64e4 /* pad rx and tx characteristics control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_WR_PREAMBLE_MODE 0x003c64e8 /* Write cycle preamble control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_EDC_DPD_CONTROL_BL 0x003c64ec /* Byte Lane GDDR5M EDC digital phase detector control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_EDC_DPD_STATUS_BL 0x003c64f0 /* Byte Lane GDDR5M EDC digital phase detector status register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_EDC_DPD_OUT_CONTROL_BL 0x003c64f4 /* Byte Lane GDDR5M EDC digital phase detector output signal control register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_EDC_DPD_OUT_STATUS_BL 0x003c64f8 /* Byte Lane GDDR5M EDC digital phase detector output signal status register */
#define BCHP_DDR34_PHY_BYTE_LANE_0_1_EDC_DPD_OUT_STATUS_CLEAR_BL 0x003c64fc /* Byte Lane GDDR5M EDC digital phase detector output signal status clear register */

#endif /* #ifndef BCHP_DDR34_PHY_BYTE_LANE_0_1_H__ */

/* End of File */
