/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jun 29 03:07:30 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008005
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_DDR34_PHY_BYTE_LANE_3_1_H__
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_H__

/***************************************************************************
 *DDR34_PHY_BYTE_LANE_3_1 - DDR34 DDR34 byte lane #3 control registers 1
 ***************************************************************************/
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_WR_DQS_P 0x003c6700 /* Byte Lane write DQS-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_WR_DQS_N 0x003c6704 /* Byte Lane write DQS-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_WR_DQ0 0x003c6708 /* Byte Lane write DQ0 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_WR_DQ1 0x003c670c /* Byte Lane write DQ1 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_WR_DQ2 0x003c6710 /* Byte Lane write DQ2 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_WR_DQ3 0x003c6714 /* Byte Lane write DQ3 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_WR_DQ4 0x003c6718 /* Byte Lane write DQ4 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_WR_DQ5 0x003c671c /* Byte Lane write DQ5 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_WR_DQ6 0x003c6720 /* Byte Lane write DQ6 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_WR_DQ7 0x003c6724 /* Byte Lane write DQ7 VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_WR_DM 0x003c6728 /* Byte Lane write DM VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_WR_EDC 0x003c672c /* Byte Lane write EDC VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQSP 0x003c6730 /* Byte Lane read DQSP VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQSN 0x003c6734 /* Byte Lane read DQSP VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ0P 0x003c6738 /* Byte Lane read DQ0-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ0N 0x003c673c /* Byte Lane read DQ0-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ1P 0x003c6740 /* Byte Lane read DQ1-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ1N 0x003c6744 /* Byte Lane read DQ1-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ2P 0x003c6748 /* Byte Lane read DQ2-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ2N 0x003c674c /* Byte Lane read DQ2-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ3P 0x003c6750 /* Byte Lane read DQ3-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ3N 0x003c6754 /* Byte Lane read DQ3-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ4P 0x003c6758 /* Byte Lane read DQ4-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ4N 0x003c675c /* Byte Lane read DQ4-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ5P 0x003c6760 /* Byte Lane read DQ5-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ5N 0x003c6764 /* Byte Lane read DQ5-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ6P 0x003c6768 /* Byte Lane read DQ6-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ6N 0x003c676c /* Byte Lane read DQ6-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ7P 0x003c6770 /* Byte Lane read DQ7-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DQ7N 0x003c6774 /* Byte Lane read DQ7-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DMP 0x003c6778 /* Byte Lane read DM-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_DMN 0x003c677c /* Byte Lane read DM-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_EDCP 0x003c6780 /* Byte Lane read EDC-P VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_EDCN 0x003c6784 /* Byte Lane read EDC-N VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CONTROL_BL_RD_EN 0x003c6788 /* Byte Lane read enable VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_VDL_CLK_CONTROL_BL 0x003c6790 /* Byte Lane write leveling VDL control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_RD_EN_DLY_CYC_BL 0x003c67a0 /* Byte Lane read enable bit-clock cycle delay control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_WL_DLY_CYC_BL 0x003c67b0 /* Byte Lane write leveling bit-clock cycle delay control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_READ_CONTROL 0x003c67b4 /* Word Lane read channel control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_READ_WATCHDOG_CONTROL 0x003c67b8 /* Word Lane read channel watchdog timer control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_READ_FIFO_ADDR 0x003c67c0 /* Word Lane read channel watchdog timer control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_READ_FIFO_DATA 0x003c67c4 /* Read fifo data register, first data */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_READ_FIFO_STATUS 0x003c67d0 /* Read fifo status register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_READ_FIFO_CLEAR 0x003c67d4 /* Read fifo status clear register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_DM_EDC_CONTROL 0x003c67d8 /* Word Lane DM & EDC signal control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_IDLE_PAD_CONTROL 0x003c67dc /* Idle mode SSTL pad control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_DRIVE_PAD_CTL 0x003c67e0 /* SSTL pad drive characteristics control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_STATIC_PAD_CTL 0x003c67e4 /* pad rx and tx characteristics control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_WR_PREAMBLE_MODE 0x003c67e8 /* Write cycle preamble control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_EDC_DPD_CONTROL_BL 0x003c67ec /* Byte Lane GDDR5M EDC digital phase detector control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_EDC_DPD_STATUS_BL 0x003c67f0 /* Byte Lane GDDR5M EDC digital phase detector status register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_EDC_DPD_OUT_CONTROL_BL 0x003c67f4 /* Byte Lane GDDR5M EDC digital phase detector output signal control register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_EDC_DPD_OUT_STATUS_BL 0x003c67f8 /* Byte Lane GDDR5M EDC digital phase detector output signal status register */
#define BCHP_DDR34_PHY_BYTE_LANE_3_1_EDC_DPD_OUT_STATUS_CLEAR_BL 0x003c67fc /* Byte Lane GDDR5M EDC digital phase detector output signal status clear register */

#endif /* #ifndef BCHP_DDR34_PHY_BYTE_LANE_3_1_H__ */

/* End of File */
